// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShamsipourOnlineSystem.Data;

namespace ShamsipourOnlineSystem.Migrations
{
    [DbContext(typeof(ShamsipourOnlineSystem_DBContext))]
    partial class ShamsipourOnlineSystem_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.DormStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StudentDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("DormStudents");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.EduExpertStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("GradReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsReversedFromGradExpert")
                        .HasColumnType("bit");

                    b.Property<string>("ReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StudentDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("EduExpertStudents");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.FinalGraduatesExpertStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StudentDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("FinalGraduatesExpertStudents");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.FinancialStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StudentDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("FinancialStudents");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.GraduatesExpertStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StudentDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("GraduatesExpertStudents");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.ItexpertStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StudentDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("ITExpertStudents");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.LaboratoryStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StudentDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("LaboratoryStudents");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.LibraryStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StudentDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("LibraryStudents");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.ResearchAssistantStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StudentDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("ResearchAssistantStudents");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.Responsible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NationalNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ResponsibleId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Responsibles");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "DormExpert"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "EduExpert"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "GraduatesExpert"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "FinancialExpert"
                        },
                        new
                        {
                            Id = 5,
                            RoleName = "ItExpert"
                        },
                        new
                        {
                            Id = 6,
                            RoleName = "LaboratoryExpert"
                        },
                        new
                        {
                            Id = 7,
                            RoleName = "LibraryExpert"
                        },
                        new
                        {
                            Id = 8,
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = 9,
                            RoleName = "ResearchExpert"
                        },
                        new
                        {
                            Id = 10,
                            RoleName = "AffairsExpert"
                        },
                        new
                        {
                            Id = 11,
                            RoleName = "ThesisExpert"
                        });
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DormId")
                        .HasColumnType("int");

                    b.Property<int?>("EduExpertId")
                        .HasColumnType("int");

                    b.Property<int?>("FinalGraduatesExpertId")
                        .HasColumnType("int");

                    b.Property<int?>("FinancialId")
                        .HasColumnType("int");

                    b.Property<int?>("GraduatesExpertId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsFinaled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPending")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsReversed")
                        .HasColumnType("bit");

                    b.Property<int?>("ItexpertId")
                        .HasColumnType("int")
                        .HasColumnName("ITExpertId");

                    b.Property<int?>("LaboratoryId")
                        .HasColumnType("int");

                    b.Property<int?>("LibraryId")
                        .HasColumnType("int");

                    b.Property<string>("NationalNo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("RequestTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ResearchAssistantId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentAffairsId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("ThesisExpertId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DormId");

                    b.HasIndex("EduExpertId");

                    b.HasIndex("FinalGraduatesExpertId");

                    b.HasIndex("FinancialId");

                    b.HasIndex("GraduatesExpertId");

                    b.HasIndex("ItexpertId");

                    b.HasIndex("LaboratoryId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("ResearchAssistantId");

                    b.HasIndex("StudentAffairsId");

                    b.HasIndex("ThesisExpertId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.StudentAffairsStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StudentDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("StudentAffairsStudents");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.ThesisExpertStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ReverseDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StageStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StudentDescribtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("ThesisExpertStudents");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.Student", b =>
                {
                    b.HasOne("ShamsipourOnlineSystem.Models.DormStudent", "Dorm")
                        .WithMany("Students")
                        .HasForeignKey("DormId")
                        .HasConstraintName("FK_Student_DormStudents");

                    b.HasOne("ShamsipourOnlineSystem.Models.EduExpertStudent", "EduExpert")
                        .WithMany("Students")
                        .HasForeignKey("EduExpertId")
                        .HasConstraintName("FK_Student_EduExpertStudents");

                    b.HasOne("ShamsipourOnlineSystem.Models.FinalGraduatesExpertStudent", "FinalGraduatesExpert")
                        .WithMany("Students")
                        .HasForeignKey("FinalGraduatesExpertId")
                        .HasConstraintName("FK_Student_FinalGraduatesExpertStudents");

                    b.HasOne("ShamsipourOnlineSystem.Models.FinancialStudent", "Financial")
                        .WithMany("Students")
                        .HasForeignKey("FinancialId")
                        .HasConstraintName("FK_Student_FinancialStudents");

                    b.HasOne("ShamsipourOnlineSystem.Models.GraduatesExpertStudent", "GraduatesExpert")
                        .WithMany("Students")
                        .HasForeignKey("GraduatesExpertId")
                        .HasConstraintName("FK_Student_GraduatesExpertStudents");

                    b.HasOne("ShamsipourOnlineSystem.Models.ItexpertStudent", "Itexpert")
                        .WithMany("Students")
                        .HasForeignKey("ItexpertId")
                        .HasConstraintName("FK_Student_ITExpertStudents");

                    b.HasOne("ShamsipourOnlineSystem.Models.LaboratoryStudent", "Laboratory")
                        .WithMany("Students")
                        .HasForeignKey("LaboratoryId")
                        .HasConstraintName("FK_Student_LaboratoryStudents");

                    b.HasOne("ShamsipourOnlineSystem.Models.LibraryStudent", "Library")
                        .WithMany("Students")
                        .HasForeignKey("LibraryId")
                        .HasConstraintName("FK_Student_LibraryStudents");

                    b.HasOne("ShamsipourOnlineSystem.Models.ResearchAssistantStudent", "ResearchAssistant")
                        .WithMany("Students")
                        .HasForeignKey("ResearchAssistantId")
                        .HasConstraintName("FK_Student_ResearchAssistantStudents");

                    b.HasOne("ShamsipourOnlineSystem.Models.StudentAffairsStudent", "StudentAffairs")
                        .WithMany("Students")
                        .HasForeignKey("StudentAffairsId")
                        .HasConstraintName("FK_Student_StudentAffairsStudents");

                    b.HasOne("ShamsipourOnlineSystem.Models.ThesisExpertStudent", "ThesisExpert")
                        .WithMany("Students")
                        .HasForeignKey("ThesisExpertId")
                        .HasConstraintName("FK_Student_ThesisExpertStudents");

                    b.Navigation("Dorm");

                    b.Navigation("EduExpert");

                    b.Navigation("FinalGraduatesExpert");

                    b.Navigation("Financial");

                    b.Navigation("GraduatesExpert");

                    b.Navigation("Itexpert");

                    b.Navigation("Laboratory");

                    b.Navigation("Library");

                    b.Navigation("ResearchAssistant");

                    b.Navigation("StudentAffairs");

                    b.Navigation("ThesisExpert");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.UserRole", b =>
                {
                    b.HasOne("ShamsipourOnlineSystem.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_UserRoles_UserRoles_RoleID")
                        .IsRequired();

                    b.HasOne("ShamsipourOnlineSystem.Models.Responsible", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserRoles_UserRoles_ResponsibleID")
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.DormStudent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.EduExpertStudent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.FinalGraduatesExpertStudent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.FinancialStudent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.GraduatesExpertStudent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.ItexpertStudent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.LaboratoryStudent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.LibraryStudent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.ResearchAssistantStudent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.Responsible", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.StudentAffairsStudent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ShamsipourOnlineSystem.Models.ThesisExpertStudent", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
